config/routes.rb
Localeze::Application.routes.draw do
  devise_for :users
  resources :base_records, :only => [:index, :show]
  root :to => 'base_records#index', :via => :get
end

app/models/base_record.rb
class BaseRecord
  include Mongoid::Document
  include Mongoid::Timestamps

  index :pid
  scope :pid, lambda{ |v| {:where => {:pid => /#{v}/i}} }

  def company_attributes
    CompanyAttribute.where :pid => self.pid
  end

  def company_headings
    CompanyHeading.where :pid => self.pid
  end

  def company_languages
    CompanyLanguage.where :pid => self.pid
  end

  def company_payment_types
    CompanyPaymentType.where :pid => self.pid
  end

  def company_phones
    CompanyPhone.where :pid => self.pid
  end

  def company_sics
    CompanySic.where :pid => self.pid
  end

  def company_unstructureds
    CompanyUnstructured.where :pid => self.pid
  end

  def custom_attributes
    CustomAttribute.where :pid => self.pid
  end
end

app/controllers/base_records_controller.rb
class BaseRecordsController < ApplicationController
  before_filter :authenticate_user!

  # CRUD ===========================================================================================
  def index
    params[:by] ||= 'pid'
    @base_records = BaseRecord.order_by(ScaffoldLogic.mongoid_sorter_from(params[:by], params[:dir])).limit(100)
    @base_records = @base_records.pid params[:q] unless params[:q].blank?
    @base_record_fields = LocalezeImport::MODEL_ATTRIBUTES[BaseRecord][:fields][0..15]
  end

  def show
    @base_record = BaseRecord.find params[:id]
  end
end

app/views/base_records/_index.html.erb
<table class="standard">
<%- if @base_record.company_attributes.blank? -%>
  <tr>
    <td><em>No records found.</em></td>
  </tr>
<%- else -%>
  <tr>
  <%- LocalezeImport::MODEL_ATTRIBUTES[model][:fields].each do |field| -%>
    <th><%= field.to_s -%></th>
  <%- end -%>
  </tr>

  <%- @base_record.send(model.name.tableize).each do |company_attribute| -%>
  <tr class="<%= cycle('odd', 'even') -%>">
    <%- LocalezeImport::MODEL_ATTRIBUTES[model][:fields].each do |field| -%>
    <td><%= company_attribute.send field -%></td>
    <%- end -%>
  </tr>
  <%- end -%>
<%- end -%>
</table>

app/views/base_records/index.html.erb
<%- @title = 'Base Records' -%>

<%= form_tag root_path, :method => :get do %>
  <%= text_field_tag 'q', params[:q], :maxlength => 40 %>
  <%= submit_tag 'Search' %>
<% end %>

<table class="standard">
<%- if @base_records.blank? -%>
  <tr>
    <td><em>No records found.</em></td>
  </tr>
<%- else -%>
  <tr>
  <%- @base_record_fields.each do |field| -%>
    <th><%= sort_link('base_records', field.to_s, params) -%></th>
  <%- end -%>
    <th> </th>
  </tr>

  <%- @base_records.each do |base_record| -%>
  <tr class="<%= cycle('odd', 'even') -%>">
  <%- @base_record_fields.each do |field| -%>
    <td><%= base_record.send field -%></td>
  <%- end -%>
    <td class="crud_links"><%= crud_links(base_record, [:show]) -%></td>
  </tr>
  <%- end -%>
<%- end -%>
</table>

app/views/base_records/show.html.erb
<%- @title = @base_record.businessname -%>

<fieldset class="form_container">
  <%= legend_tag 'About' -%>

<%- LocalezeImport::MODEL_ATTRIBUTES[BaseRecord][:fields].each do |field| -%>
  <div class="form_column">
    <%= faux_field field.to_s.titleize, @base_record.send(field) -%>
  </div>
<%- end -%>
</fieldset>

<div class="link_block attached">
  <%= link_to 'Back', base_records_path, :class => 'link_button' -%>
</div>

<fieldset class="form_container">
  <%= legend_tag 'Company Attributes' -%><br />
  <%= render :partial => 'index', :locals => {:model => CompanyAttribute} -%>
</fieldset>

<fieldset class="form_container">
  <%= legend_tag 'Company Headings' -%><br />
  <%= render :partial => 'index', :locals => {:model => CompanyHeading} -%>
</fieldset>

<fieldset class="form_container">
  <%= legend_tag 'Company Languages' -%><br />
  <%= render :partial => 'index', :locals => {:model => CompanyLanguage} -%>
</fieldset>

<fieldset class="form_container">
  <%= legend_tag 'Company Payment Types' -%><br />
  <%= render :partial => 'index', :locals => {:model => CompanyPaymentType} -%>
</fieldset>

<fieldset class="form_container">
  <%= legend_tag 'Company Phones' -%><br />
  <%= render :partial => 'index', :locals => {:model => CompanyPhone} -%>
</fieldset>

<fieldset class="form_container">
  <%= legend_tag 'Company Sics' -%><br />
  <%= render :partial => 'index', :locals => {:model => CompanySic} -%>
</fieldset>

<fieldset class="form_container">
  <%= legend_tag 'Company unstructureds' -%><br />
  <%= render :partial => 'index', :locals => {:model => CompanyUnstructured} -%>
</fieldset>

<fieldset class="form_container">
  <%= legend_tag 'Custom Attributes' -%><br />
  <%= render :partial => 'index', :locals => {:model => CustomAttribute} -%>
</fieldset>